{"url": "https://www.thegioididong.com/dtdd/samsung-galaxy-note-10-plus"}
{"url": "https://www.thegioididong.com/dtdd/vivo-y19"}
{"url": "https://www.thegioididong.com/dtdd/samsung-galaxy-a70"}
{"url": "https://www.thegioididong.com/dtdd/iphone-11"}
{"url": "https://www.thegioididong.com/dtdd/oppo-reno2-f-xanh-tinh-van"}
{"url": "https://www.thegioididong.com/dtdd/samsung-galaxy-a30s"}
{"url": "https://www.thegioididong.com/dtdd/xiaomi-redmi-8-64gb"}
{"url": "https://www.thegioididong.com/dtdd/oppo-a5-2020"}
{"url": "https://www.thegioididong.com/dtdd/iphone-11-pro-max-512gb"}
{"url": "https://www.thegioididong.com/dtdd/iphone-11-pro-max-256gb"}
{"url": "https://www.thegioididong.com/dtdd/iphone-11-pro-256gb"}
{"url": "https://www.thegioididong.com/dtdd/iphone-11-pro-max"}
{"url": "https://www.thegioididong.com/dtdd/iphone-xs-max-256gb"}
{"url": "https://www.thegioididong.com/dtdd/iphone-xs-256gb"}
{"url": "https://www.thegioididong.com/dtdd/samsung-galaxy-s10-plus-512gb"}
{"url": "https://www.thegioididong.com/dtdd/iphone-xs-max"}
{"url": "https://www.thegioididong.com/dtdd/iphone-xs"}
{"url": "https://www.thegioididong.com/dtdd/iphone-11-128gb"}
{"url": "https://www.thegioididong.com/dtdd/samsung-galaxy-note-10"}
{"url": "https://www.thegioididong.com/dtdd/samsung-galaxy-note-9"}
{"url": "https://www.thegioididong.com/dtdd/samsung-galaxy-s10-plus"}
{"url": "https://www.thegioididong.com/dtdd/huawei-p30-pro"}
{"url": "https://www.thegioididong.com/dtdd/oppo-reno-10x-zoom-edition"}
{"url": "https://www.thegioididong.com/dtdd/iphone-xr-128gb"}
{"url": "https://www.thegioididong.com/dtdd/iphone-8-plus"}
{"url": "https://www.thegioididong.com/dtdd/blackberry-key2"}
{"url": "https://www.thegioididong.com/dtdd/samsung-galaxy-a80"}
{"url": "https://www.thegioididong.com/dtdd/oppo-reno2"}
{"url": "https://www.thegioididong.com/dtdd/iphone-7-plus"}
{"url": "https://www.thegioididong.com/dtdd/oppo-reno"}
{"url": "https://www.thegioididong.com/dtdd/samsung-galaxy-a9-2018"}
{"url": "https://www.thegioididong.com/dtdd/blackberry-key2-le"}
{"url": "https://www.thegioididong.com/dtdd/iphone-7"}
{"url": "https://www.thegioididong.com/dtdd/vivo-v17-pro"}
{"url": "https://www.thegioididong.com/dtdd/oppo-reno2-f"}
{"url": "https://www.thegioididong.com/dtdd/iphone-6s-plus-32gb"}
{"url": "https://www.thegioididong.com/dtdd/oppo-f11-pro-128gb"}
{"url": "https://www.thegioididong.com/dtdd/xiaomi-mi-9-se"}
{"url": "https://www.thegioididong.com/dtdd/samsung-galaxy-a50-128gb"}
{"url": "https://www.thegioididong.com/dtdd/xiaomi-mi-9t"}
{"url": "https://www.thegioididong.com/dtdd/realme-xt"}
{"url": "https://www.thegioididong.com/dtdd/samsung-galaxy-a7-2018-128gb"}
{"url": "https://www.thegioididong.com/dtdd/blackberry-keyone"}
{"url": "https://www.thegioididong.com/dtdd/oppo-f11"}
{"url": "https://www.thegioididong.com/dtdd/samsung-galaxy-a50s"}
{"url": "https://www.thegioididong.com/dtdd/samsung-galaxy-a50"}
{"url": "https://www.thegioididong.com/dtdd/samsung-galaxy-a7-2018"}
{"url": "https://www.thegioididong.com/dtdd/oppo-a9"}
{"url": "https://www.thegioididong.com/dtdd/oppo-k3"}
{"url": "https://www.thegioididong.com/dtdd/realme-5-pro-8gb"}
{"url": "https://www.thegioididong.com/dtdd/blackberry-keyone-3gb-32gb"}
{"url": "https://www.thegioididong.com/dtdd/blackberry-evolve"}
{"url": "https://www.thegioididong.com/dtdd/huawei-p30-lite"}
{"url": "https://www.thegioididong.com/dtdd/xiaomi-redmi-note-8-pro-6gb-128gb"}
{"url": "https://www.thegioididong.com/dtdd/xiaomi-redmi-note-8-pro-6gb-128gb-xanh-duong"}
{"url": "https://www.thegioididong.com/dtdd/nokia-72"}
{"url": "https://www.thegioididong.com/dtdd/xiaomi-redmi-note-8-pro"}
{"url": "https://www.thegioididong.com/dtdd/realme-5-pro"}
{"url": "https://www.thegioididong.com/dtdd/xiaomi-redmi-note-8-pro-6gb-64gb-xanh-duong"}
{"url": "https://www.thegioididong.com/dtdd/realme-3-pro"}
{"url": "https://www.thegioididong.com/dtdd/huawei-nova-3i"}
{"url": "https://www.thegioididong.com/dtdd/samsung-galaxy-a30"}
{"url": "https://www.thegioididong.com/dtdd/xiaomi-redmi-note-8-128gb"}
{"url": "https://www.thegioididong.com/dtdd/huawei-y9-prime-2019"}
{"url": "https://www.thegioididong.com/dtdd/vivo-v15-64gb"}
{"url": "https://www.thegioididong.com/dtdd/samsung-galaxy-a20s"}
{"url": "https://www.thegioididong.com/dtdd/oppo-a5-2020-128gb"}
{"url": "https://www.thegioididong.com/dtdd/xiaomi-redmi-note-8"}
{"url": "https://www.thegioididong.com/dtdd/realme-5-4gb"}
{"url": "https://www.thegioididong.com/dtdd/xiaomi-redmi-note-7"}
{"url": "https://www.thegioididong.com/dtdd/samsung-galaxy-a30-32gb"}
{"url": "https://www.thegioididong.com/dtdd/oppo-a7"}
{"url": "https://www.thegioididong.com/dtdd/oppo-f9"}
{"url": "https://www.thegioididong.com/dtdd/samsung-galaxy-m20"}
{"url": "https://www.thegioididong.com/dtdd/xiaomi-mi-a3"}
{"url": "https://www.thegioididong.com/dtdd/samsung-galaxy-a20s-32gb"}
{"url": "https://www.thegioididong.com/dtdd/vivo-y17"}
{"url": "https://www.thegioididong.com/dtdd/samsung-galaxy-a20"}
{"url": "https://www.thegioididong.com/dtdd/xiaomi-redmi-note-8-32gb"}
{"url": "https://www.thegioididong.com/dtdd/realme-5"}
{"url": "https://www.thegioididong.com/dtdd/realme-3"}
{"url": "https://www.thegioididong.com/dtdd/nokia-61-plus"}
{"url": "https://www.thegioididong.com/dtdd/vivo-v11i"}
{"url": "https://www.thegioididong.com/dtdd/vsmart-live-6gb"}
{"url": "https://www.thegioididong.com/dtdd/samsung-galaxy-a10s"}
{"url": "https://www.thegioididong.com/dtdd/oppo-a5s"}
{"url": "https://www.thegioididong.com/dtdd/xiaomi-redmi-7"}
{"url": "https://www.thegioididong.com/dtdd/vivo-y12"}
{"url": "https://www.thegioididong.com/dtdd/vsmart-live"}
{"url": "https://www.thegioididong.com/dtdd/huawei-y7-pro-2019"}
{"url": "https://www.thegioididong.com/dtdd/vivo-y91"}
{"url": "https://www.thegioididong.com/dtdd/nokia-51-plus"}
{"url": "https://www.thegioididong.com/dtdd/nokia-32"}
{"url": "https://www.thegioididong.com/dtdd/oppo-a1k"}
{"url": "https://www.thegioididong.com/dtdd/samsung-galaxy-a10"}
{"url": "https://www.thegioididong.com/dtdd/vivo-y11"}
{"url": "https://www.thegioididong.com/dtdd/xiaomi-redmi-8"}
{"url": "https://www.thegioididong.com/dtdd/xiaomi-redmi-7-16gb"}
{"url": "https://www.thegioididong.com/dtdd/realme-c2"}
{"url": "https://www.thegioididong.com/dtdd/vivo-y91c"}
{"url": "https://www.thegioididong.com/dtdd/xiaomi-redmi-8a"}
{"url": "https://www.thegioididong.com/dtdd/vsmart-joy-2-plus-2gb"}
{"url": "https://www.thegioididong.com/dtdd/realme-c2-16gb"}
{"url": "https://www.thegioididong.com/dtdd/realme-c2-2gb-32gb"}
{"url": "https://www.thegioididong.com/dtdd/nokia-800-tough"}
{"url": "https://www.thegioididong.com/dtdd/nokia-32-16gb"}
{"url": "https://www.thegioididong.com/dtdd/xiaomi-redmi-7a"}
{"url": "https://www.thegioididong.com/dtdd/coolpad-n5"}
{"url": "https://www.thegioididong.com/dtdd/vsmart-star"}
{"url": "https://www.thegioididong.com/dtdd/nokia-2720-2019"}
{"url": "https://www.thegioididong.com/dtdd/itel-s15-pro"}
{"url": "https://www.thegioididong.com/dtdd/xiaomi-redmi-go-16gb"}
{"url": "https://www.thegioididong.com/dtdd/mobell-s61"}
{"url": "https://www.thegioididong.com/dtdd/mobell-nova-p3"}
{"url": "https://www.thegioididong.com/dtdd/itel-p15"}
{"url": "https://www.thegioididong.com/dtdd/vsmart-bee"}
{"url": "https://www.thegioididong.com/dtdd/itel-s33"}
{"url": "https://www.thegioididong.com/dtdd/itel-p33"}
{"url": "https://www.thegioididong.com/dtdd/mobell-s60"}
{"url": "https://www.thegioididong.com/dtdd/masstel-x5-fami"}
{"url": "https://www.thegioididong.com/dtdd/mobell-s51"}
{"url": "https://www.thegioididong.com/dtdd/coolpad-n3c"}
{"url": "https://www.thegioididong.com/dtdd/nokia-230-khong-the"}
{"url": "https://www.thegioididong.com/dtdd/nokia-3310-2017"}
{"url": "https://www.thegioididong.com/dtdd/mobell-s41"}
{"url": "https://www.thegioididong.com/dtdd/itel-alpha-lite"}
{"url": "https://www.thegioididong.com/dtdd/nokia-210"}
{"url": "https://www.thegioididong.com/dtdd/nokia-150-khong-the-nho"}
{"url": "https://www.thegioididong.com/dtdd/mobell-m729"}
{"url": "https://www.thegioididong.com/dtdd/mobell-rock-3"}
{"url": "https://www.thegioididong.com/dtdd/nokia-130-2017"}
{"url": "https://www.thegioididong.com/dtdd/masstel-fami-12"}
{"url": "https://www.thegioididong.com/dtdd/nokia-110-2019"}
{"url": "https://www.thegioididong.com/dtdd/mobell-m529"}
{"url": "https://www.thegioididong.com/dtdd/masstel-izi-300"}
{"url": "https://www.thegioididong.com/dtdd/nokia-106-2018"}
{"url": "https://www.thegioididong.com/dtdd/itel-it5092"}
{"url": "https://www.thegioididong.com/dtdd/mobell-m889"}
{"url": "https://www.thegioididong.com/dtdd/mobell-m389"}
{"url": "https://www.thegioididong.com/dtdd/nokia-105-single-sim-2019"}
{"url": "https://www.thegioididong.com/dtdd/nokia-105-single-sim-2017"}
{"url": "https://www.thegioididong.com/dtdd/masstel-izi-280"}
{"url": "https://www.thegioididong.com/dtdd/itel-it6120"}
{"url": "https://www.thegioididong.com/dtdd/coolpad-f129"}
{"url": "https://www.thegioididong.com/dtdd/masstel-izi-206"}
{"url": "https://www.thegioididong.com/dtdd/mobell-m339"}
{"url": "https://www.thegioididong.com/dtdd/coolpad-f210"}
{"url": "https://www.thegioididong.com/dtdd/itel-it5025"}
{"url": "https://www.thegioididong.com/dtdd/coolpad-f126"}
{"url": "https://www.thegioididong.com/dtdd/itel-it2171"}
{"url": "https://www.thegioididong.com/dtdd/mobell-m229-2019"}
{"url": "https://www.thegioididong.com/dtdd/masstel-izi-112"}
{"url": "https://www.thegioididong.com/dtdd/coolpad-f116"}
{"url": "https://www.thegioididong.com/dtdd/coolpad-f110"}
{"url": "https://www.thegioididong.com/dtdd/mobell-m228"}
{"url": "https://www.thegioididong.com/dtdd/masstel-izi-120"}
{"url": "https://www.thegioididong.com/dtdd/mobell-m217"}
{"url": "https://www.thegioididong.com/dtdd/itel-value-100"}
{"url": "https://www.thegioididong.com/dtdd/itel-it2161"}
