{"url": "https://www.thegioididong.com/may-tinh-bang/ipad-10-2-inch-wifi-cellular-32gb-2019"}
{"url": "https://www.thegioididong.com/may-tinh-bang/ipad-wifi-32gb-2018"}
{"url": "https://www.thegioididong.com/may-tinh-bang/ipad-10-2-inch-wifi-32gb-2019"}
{"url": "https://www.thegioididong.com/may-tinh-bang/samsung-galaxy-tab-a8-plus-p205"}
{"url": "https://www.thegioididong.com/may-tinh-bang/samsung-galaxy-tab-s6"}
{"url": "https://www.thegioididong.com/may-tinh-bang/samsung-galaxy-tab-a-101-t515-2019"}
{"url": "https://www.thegioididong.com/may-tinh-bang/huawei-mediapad-t5"}
{"url": "https://www.thegioididong.com/may-tinh-bang/lenovo-tab-4-8-tb-8504x"}
{"url": "https://www.thegioididong.com/may-tinh-bang/ipad-pro-11-inch-2018-64gb-wifi"}
{"url": "https://www.thegioididong.com/may-tinh-bang/ipad-10-2-inch-wifi-cellular-128gb-2019"}
{"url": "https://www.thegioididong.com/may-tinh-bang/ipad-mini-79-inch-wifi-cellular-64gb-2019"}
{"url": "https://www.thegioididong.com/may-tinh-bang/ipad-air-105-inch-wifi-2019"}
{"url": "https://www.thegioididong.com/may-tinh-bang/ipad-10-2-inch-wifi-128gb-2019"}
{"url": "https://www.thegioididong.com/may-tinh-bang/ipad-wifi-128-gb-2018"}
{"url": "https://www.thegioididong.com/may-tinh-bang/ipad-mini-79-inch-wifi-2019"}
{"url": "https://www.thegioididong.com/may-tinh-bang/samsung-galaxy-tab-a-105-inch"}
{"url": "https://www.thegioididong.com/may-tinh-bang/huawei-mediapad-t3-10"}
{"url": "https://www.thegioididong.com/may-tinh-bang/lenovo-tab-e10-tb-x104l-den"}
{"url": "https://www.thegioididong.com/may-tinh-bang/samsung-galaxy-tab-a8-t295-2019"}
{"url": "https://www.thegioididong.com/may-tinh-bang/huawei-mediapad-t3-80"}
{"url": "https://www.thegioididong.com/may-tinh-bang/masstel-tab10-pro"}
{"url": "https://www.thegioididong.com/may-tinh-bang/huawei-mediapad-t3-7-2019"}
{"url": "https://www.thegioididong.com/may-tinh-bang/mobell-tab-10"}
{"url": "https://www.thegioididong.com/may-tinh-bang/mobell-tab-8-pro"}
{"url": "https://www.thegioididong.com/may-tinh-bang/masstel-tab8-pro"}
{"url": "https://www.thegioididong.com/may-tinh-bang/lenovo-tab-e7-tb-7104i"}
{"url": "https://www.thegioididong.com/may-tinh-bang/mobell-tab-8a"}
{"url": "https://www.thegioididong.com/may-tinh-bang/mobell-tab-7s"}
